[project]
name = "similie-examples"
version = "0.0.0"
description = "Dependencies for examples with compile-time code generation."
requires-python = ">=3.9"
dependencies = ["sympy>=1.12"]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"
